var node = document.createElement("DIV");
node.classList.add("box");
var link1 = document.createElement("A");
link1.classList.add("link");
link1.setAttribute("href", "");
var textnode = document.createTextNode("Images for sachin tendulkar");
link1.appendChild(textnode);
node.appendChild(link1);
node.appendChild(document.createElement("BR"));
var imgDiv = document.createElement("DIV");
imgDiv.classList.add("carousel");
var innerDiv = document.createElement("DIV");
innerDiv.classList.add("slide");
var img = document.createElement("IMG");
img.setAttribute("src", "./images/sachin1.jpeg");
innerDiv.appendChild(img);
imgDiv.appendChild(innerDiv);
var innerDiv = document.createElement("DIV");
innerDiv.classList.add("slide");
img = document.createElement("IMG");
img.setAttribute("src", "./images/sachin2.jpeg");
innerDiv.appendChild(img);
imgDiv.appendChild(innerDiv);
var innerDiv = document.createElement("DIV");
innerDiv.classList.add("slide");
img = document.createElement("IMG");
img.setAttribute("src", "./images/sachin3.jpeg");
innerDiv.appendChild(img);
imgDiv.appendChild(innerDiv);
var innerDiv = document.createElement("DIV");
innerDiv.classList.add("slide");
img = document.createElement("IMG");
img.setAttribute("src", "./images/sachin4.jpeg");
innerDiv.appendChild(img);
imgDiv.appendChild(innerDiv);
var innerDiv = document.createElement("DIV");
innerDiv.classList.add("slide");
img = document.createElement("IMG");
img.setAttribute("src", "./images/sachin5.jpeg");
innerDiv.appendChild(img);
imgDiv.appendChild(innerDiv);
var innerDiv = document.createElement("DIV");
innerDiv.classList.add("slide");
img = document.createElement("IMG");
img.setAttribute("src", "./images/sachin6.jpeg");
innerDiv.appendChild(img);
imgDiv.appendChild(innerDiv);
node.appendChild(imgDiv);
document.getElementsByClassName("parent")[0].appendChild(node);



var node = document.createElement("DIV");
node.classList.add("box");
var link1 = document.createElement("A");
link1.classList.add("link");
link1.setAttribute("href", "");
var textnode = document.createTextNode("Sachin Tendulkar - Wikipedia");
link1.appendChild(textnode);
node.appendChild(link1);
var para1 = document.createElement("P");
textnode = document.createTextNode("Sachin Ramesh Tendulkar born 24 April 1973 is an Indian former international cricketer and a former captain of the Indian national team. He is widely regarded as one of the greatest batsmen in the history of cricket. He is the highest run scorer of all time in International cricket.");
para1.appendChild(textnode);
node.appendChild(para1);
var ul1 = document.createElement("UL");
var li1 = document.createElement("LI");
var bold1 = document.createElement("B");
textnode = document.createTextNode("ODI debut (cap 74)");
var text2 = document.createTextNode(": 18 December 1989 vs Pakistan");
bold1.appendChild(textnode);
li1.appendChild(bold1);
li1.appendChild(text2);
ul1.appendChild(li1);
li1 = document.createElement("LI");
bold1 = document.createElement("B");
textnode = document.createTextNode("Last ODI");
text2 = document.createTextNode(": 18th March 2012 vs Pak");
bold1.appendChild(textnode);
li1.appendChild(bold1);
li1.appendChild(text2);
ul1.appendChild(li1);
node.appendChild(ul1);
document.getElementsByClassName("parent")[0].appendChild(node);


node = document.createElement("DIV");
node.classList.add("box");
var link1 = document.createElement("A");
link1.classList.add("link");
link1.setAttribute("href", "");
var textnode = document.createTextNode("Sachin Tendulkar Profile - ICC Ranking, Age, Career Info..");
link1.appendChild(textnode);
node.appendChild(link1);
var para1 = document.createElement("P");
textnode = document.createTextNode("Sachin Ramesh Tendulkar was that cricketer whose personality and aura upstaged any cricketing contest; yet he maintained that he wasn't greater than than the ...");
para1.appendChild(textnode);
node.appendChild(para1);
var ul1 = document.createElement("UL");
var li1 = document.createElement("LI");
var bold1 = document.createElement("B");
var text2 = document.createTextNode("Pakistan vs India");
li1.appendChild(bold1);
li1.appendChild(text2);
ul1.appendChild(li1);
li1 = document.createElement("LI");
bold1 = document.createElement("B");
textnode = document.createTextNode("1st Test");
text2 = document.createTextNode(": 5th March, india vs Pak");
bold1.appendChild(textnode);
li1.appendChild(bold1);
li1.appendChild(text2);
ul1.appendChild(li1);
node.appendChild(ul1);
document.getElementsByClassName("parent")[0].appendChild(node);


node = document.createElement("DIV");
node.classList.add("box");
var link1 = document.createElement("A");
link1.classList.add("link");
link1.setAttribute("href", "");
var textnode = document.createTextNode("Sachin Tendulkar Home - Facebook");
link1.appendChild(textnode);
node.appendChild(link1);
var para1 = document.createElement("P");
textnode = document.createTextNode("Sachin Tendulkar. 28255148 likes · 415708 talking about this. The Official Facebook page of Sachin Tendulkar.");
para1.appendChild(textnode);
node.appendChild(para1);
document.getElementsByClassName("parent")[0].appendChild(node);